export { default as HomeLayout } from './HomeLayout'
export { default as Landing } from './Landing'
export { default as About } from './About'
export { default as Deals } from './Deals'
export { default as Result } from './Result'
export { default as Users } from './Users'
export { default as Gallery } from './Gallery'
